#!/bin/bash
Begin() {
    echo
    read -p "Commande --> " command
    echo

if [ $command == "exit" ]; then
    echo bye bye
    echo
else
    clear
    php "/Users/tom/Desktop/Tom Dofus/Dofus.php" $command
    Begin
fi
}
Begin